# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Rcpp_PointMap_createFromGrid <- function(minX, minY, maxX, maxY, gridSize) {
    .Call('_alcyon_createFromGrid', PACKAGE = 'alcyon', minX, minY, maxX, maxY, gridSize)
}

Rcpp_PointMap_blockLines <- function(pointMapPtr, boundaryMapPtr) {
    invisible(.Call('_alcyon_blockLines', PACKAGE = 'alcyon', pointMapPtr, boundaryMapPtr))
}

Rcpp_PointMap_fill <- function(pointMapPtr, pointCoords) {
    invisible(.Call('_alcyon_fill', PACKAGE = 'alcyon', pointMapPtr, pointCoords))
}

Rcpp_PointMap_makeGraph <- function(pointMapPtr, boundaryGraph, maxVisibility) {
    .Call('_alcyon_makeGraph', PACKAGE = 'alcyon', pointMapPtr, boundaryGraph, maxVisibility)
}

Rcpp_PointMap_unmakeGraph <- function(pointMapPtr, removeLinksWhenUnmaking) {
    invisible(.Call('_alcyon_unmakeGraph', PACKAGE = 'alcyon', pointMapPtr, removeLinksWhenUnmaking))
}

Rcpp_PointMap_getName <- function(pointMapPtr) {
    .Call('_alcyon_pointMapGetName', PACKAGE = 'alcyon', pointMapPtr)
}

Rcpp_PointMap_getLinks <- function(pointMapPtr) {
    .Call('_alcyon_pointMapGetLinks', PACKAGE = 'alcyon', pointMapPtr)
}

Rcpp_PointMap_getConnections <- function(pointMapPtr) {
    .Call('_alcyon_pointMapGetConnections', PACKAGE = 'alcyon', pointMapPtr)
}

Rcpp_PointMap_getFilledPoints <- function(pointMapPtr) {
    .Call('_alcyon_getFilledPoints', PACKAGE = 'alcyon', pointMapPtr)
}

Rcpp_ShapeGraph_getAxialConnections <- function(shapeGraphPtr) {
    .Call('_alcyon_getAxialConnections', PACKAGE = 'alcyon', shapeGraphPtr)
}

Rcpp_ShapeGraph_getSegmentConnections <- function(shapeGraphPtr) {
    .Call('_alcyon_getSegmentConnections', PACKAGE = 'alcyon', shapeGraphPtr)
}

Rcpp_ShapeGraph_getLinksUnlinks <- function(shapeGraphPtr) {
    .Call('_alcyon_getLinksUnlinks', PACKAGE = 'alcyon', shapeGraphPtr)
}

Rcpp_ShapeMap_make <- function(name) {
    .Call('_alcyon_make', PACKAGE = 'alcyon', name)
}

Rcpp_ShapeMap_getName <- function(shapeMap) {
    .Call('_alcyon_getName', PACKAGE = 'alcyon', shapeMap)
}

Rcpp_ShapeMap_getAttributeNames <- function(shapeMap) {
    .Call('_alcyon_getAttributeNames', PACKAGE = 'alcyon', shapeMap)
}

Rcpp_ShapeMap_getAttributeData <- function(shapeMap, attributeNames) {
    .Call('_alcyon_getAttributeData', PACKAGE = 'alcyon', shapeMap, attributeNames)
}

Rcpp_ShapeMap_getShapesAsLineCoords <- function(shapeMap) {
    .Call('_alcyon_getShapesAsLineCoords', PACKAGE = 'alcyon', shapeMap)
}

Rcpp_ShapeMap_getShapesAsPolygonCoords <- function(shapeMap) {
    .Call('_alcyon_getShapesAsPolygonCoords', PACKAGE = 'alcyon', shapeMap)
}

Rcpp_ShapeMap_getShapeCoords <- function(shapeMapPtr, ref) {
    .Call('_alcyon_getShapeCoords', PACKAGE = 'alcyon', shapeMapPtr, ref)
}

Rcpp_ShapeMap_getShapeAttributes <- function(shapeMapPtr, ref) {
    .Call('_alcyon_getShapeAttributes', PACKAGE = 'alcyon', shapeMapPtr, ref)
}

Rcpp_agentAnalysis <- function(pointMapPtr, systemTimesteps, releaseRate, agentLifeTimesteps, agentFov, agentStepsToDecision, agentLookMode, agentReleaseLocations, randomReleaseLocationSeed, recordTrailForAgents, getGateCounts, verbose) {
    .Call('_alcyon_agentAnalysis', PACKAGE = 'alcyon', pointMapPtr, systemTimesteps, releaseRate, agentLifeTimesteps, agentFov, agentStepsToDecision, agentLookMode, agentReleaseLocations, randomReleaseLocationSeed, recordTrailForAgents, getGateCounts, verbose)
}

Rcpp_makeAllLineMap <- function(boundsMap, seedX, seedY) {
    .Call('_alcyon_makeAllLineMap', PACKAGE = 'alcyon', boundsMap, seedX, seedY)
}

Rcpp_extractFewestLineMaps <- function(allLineMap) {
    .Call('_alcyon_extractFewestLineMaps', PACKAGE = 'alcyon', allLineMap)
}

Rcpp_runAxialAnalysis <- function(shapeGraph, radii, weightedMeasureColNameNV = NULL, includeChoiceNV = NULL, includeIntermediateMetricsNV = NULL, verboseNV = NULL, progressNV = NULL) {
    .Call('_alcyon_runAxialAnalysis', PACKAGE = 'alcyon', shapeGraph, radii, weightedMeasureColNameNV, includeChoiceNV, includeIntermediateMetricsNV, verboseNV, progressNV)
}

Rcpp_runAxialLocalAnalysis <- function(shapeGraph, verboseNV = NULL, progressNV = NULL) {
    .Call('_alcyon_runAxialLocalAnalysis', PACKAGE = 'alcyon', shapeGraph, verboseNV, progressNV)
}

Rcpp_axialStepDepth <- function(shapeGraph, stepType, stepDepthPointsX, stepDepthPointsY, verboseNV = NULL, progressNV = NULL) {
    .Call('_alcyon_axialStepDepth', PACKAGE = 'alcyon', shapeGraph, stepType, stepDepthPointsX, stepDepthPointsY, verboseNV, progressNV)
}

Rcpp_getSfShapeMapExpectedColName <- function(df, rColIdx) {
    .Call('_alcyon_getSfShapeMapExpectedColName', PACKAGE = 'alcyon', df, rColIdx)
}

Rcpp_getAxialToSegmentExpectedColName <- function(colName) {
    .Call('_alcyon_getAxialToSegmentExpectedColName', PACKAGE = 'alcyon', colName)
}

Rcpp_toShapeMap <- function(df, keepColumnIdxsNV = NULL) {
    .Call('_alcyon_toShapeMap', PACKAGE = 'alcyon', df, keepColumnIdxsNV)
}

Rcpp_toAxialShapeGraph <- function(shapeMap, nameNV = NULL, copydataNV = NULL) {
    .Call('_alcyon_toAxialShapeGraph', PACKAGE = 'alcyon', shapeMap, nameNV, copydataNV)
}

Rcpp_axialToSegment <- function(shapeGraph, nameNV = NULL, copydataNV = NULL, stubremovalNV = NULL) {
    .Call('_alcyon_axialToSegment', PACKAGE = 'alcyon', shapeGraph, nameNV, copydataNV, stubremovalNV)
}

Rcpp_shapeMapToSegment <- function(shapeMap, nameNV = NULL, keeporiginalNV = NULL, copydataNV = NULL, stubremovalNV = NULL) {
    .Call('_alcyon_shapeMapToSegment', PACKAGE = 'alcyon', shapeMap, nameNV, keeporiginalNV, copydataNV, stubremovalNV)
}

Rcpp_makeIsovists <- function(boundsMap, pointCoords, directionAngles, fieldOfViewAngles, simple_version) {
    .Call('_alcyon_makeIsovists', PACKAGE = 'alcyon', boundsMap, pointCoords, directionAngles, fieldOfViewAngles, simple_version)
}

Rcpp_ShapeGraph_linkCoords <- function(shapeGraphPtr, coords) {
    invisible(.Call('_alcyon_shapeGraphLinkCoords', PACKAGE = 'alcyon', shapeGraphPtr, coords))
}

Rcpp_ShapeGraph_linkRefs <- function(shapeGraphPtr, refs) {
    invisible(.Call('_alcyon_shapeGraphLinkRefs', PACKAGE = 'alcyon', shapeGraphPtr, refs))
}

Rcpp_PointMap_linkCoords <- function(pointMapPtr, coords) {
    invisible(.Call('_alcyon_pointMapLinkCoords', PACKAGE = 'alcyon', pointMapPtr, coords))
}

Rcpp_PointMap_linkRefs <- function(pointMapPtr, refs) {
    invisible(.Call('_alcyon_pointMapLinkRefs', PACKAGE = 'alcyon', pointMapPtr, refs))
}

Rcpp_ShapeGraph_unlinkCoords <- function(shapeGraphPtr, coords) {
    invisible(.Call('_alcyon_shapeMapUnlinkCoords', PACKAGE = 'alcyon', shapeGraphPtr, coords))
}

Rcpp_ShapeGraph_unlinkAtCrossPoint <- function(shapeGraphPtr, coords) {
    invisible(.Call('_alcyon_shapeGraphUnlinkAtCrossPoint', PACKAGE = 'alcyon', shapeGraphPtr, coords))
}

Rcpp_ShapeGraph_unlinkRefs <- function(shapeGraphPtr, refs) {
    invisible(.Call('_alcyon_shapeMapUnlinkRefs', PACKAGE = 'alcyon', shapeGraphPtr, refs))
}

Rcpp_PointMap_unlinkCoords <- function(pointMapPtr, coords) {
    invisible(.Call('_alcyon_pointMapUnlinkCoords', PACKAGE = 'alcyon', pointMapPtr, coords))
}

Rcpp_PointMap_unlinkRefs <- function(pointMapPtr, refs) {
    invisible(.Call('_alcyon_pointMapUnlinkRefs', PACKAGE = 'alcyon', pointMapPtr, refs))
}

Rcpp_MetaGraph_read <- function(fileName, verboseNV = NULL) {
    .Call('_alcyon_readMetaGraph', PACKAGE = 'alcyon', fileName, verboseNV)
}

Rcpp_runSegmentAnalysis <- function(shapeGraph, radii, radiusStepType, analysisStepType, weightedMeasureColNameNV = NULL, includeChoiceNV = NULL, tulipBinsNV = NULL, verboseNV = NULL, selOnlyNV = NULL, progressNV = NULL) {
    .Call('_alcyon_runSegmentAnalysis', PACKAGE = 'alcyon', shapeGraph, radii, radiusStepType, analysisStepType, weightedMeasureColNameNV, includeChoiceNV, tulipBinsNV, verboseNV, selOnlyNV, progressNV)
}

Rcpp_segmentStepDepth <- function(shapeGraph, stepType, stepDepthPointsX, stepDepthPointsY, tulipBinsNV = NULL, verboseNV = NULL, progressNV = NULL) {
    .Call('_alcyon_segmentStepDepth', PACKAGE = 'alcyon', shapeGraph, stepType, stepDepthPointsX, stepDepthPointsY, tulipBinsNV, verboseNV, progressNV)
}

Rcpp_VGA_throughVision <- function(pointMapPtr) {
    .Call('_alcyon_vgaThroughVision', PACKAGE = 'alcyon', pointMapPtr)
}

Rcpp_VGA_angular <- function(pointMapPtr, radius, gatesOnly) {
    .Call('_alcyon_vgaAngular', PACKAGE = 'alcyon', pointMapPtr, radius, gatesOnly)
}

Rcpp_VGA_metric <- function(pointMapPtr, radius, gatesOnly) {
    .Call('_alcyon_vgaMetric', PACKAGE = 'alcyon', pointMapPtr, radius, gatesOnly)
}

Rcpp_VGA_visualGlobal <- function(pointMapPtr, radius, gatesOnly) {
    .Call('_alcyon_vgaVisualGlobal', PACKAGE = 'alcyon', pointMapPtr, radius, gatesOnly)
}

Rcpp_VGA_visualLocal <- function(pointMapPtr, gatesOnly) {
    .Call('_alcyon_vgaVisualLocal', PACKAGE = 'alcyon', pointMapPtr, gatesOnly)
}

Rcpp_VGA_isovist <- function(pointMapPtr, shapeMapPtr) {
    .Call('_alcyon_vgaIsovist', PACKAGE = 'alcyon', pointMapPtr, shapeMapPtr)
}

Rcpp_VGA_visualDepth <- function(pointMapPtr, stepDepthPoints) {
    .Call('_alcyon_vgaVisualDepth', PACKAGE = 'alcyon', pointMapPtr, stepDepthPoints)
}

Rcpp_VGA_metricDepth <- function(pointMapPtr, stepDepthPoints) {
    .Call('_alcyon_vgaMetricDepth', PACKAGE = 'alcyon', pointMapPtr, stepDepthPoints)
}

Rcpp_VGA_angularDepth <- function(pointMapPtr, stepDepthPoints) {
    .Call('_alcyon_vgaAngularDepth', PACKAGE = 'alcyon', pointMapPtr, stepDepthPoints)
}

